server:
  port: 8080

spring:
  application:
    name: cloud-nacos-file-server
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: localhost:8848
  servlet:
    multipart:
      enabled: false



